version: 2
updates:
  - package-ecosystem: npm
    directory: "/frontend"
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    groups:
      all:
        update-types: [minor, patch]
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: pip
    directory: "/backend"
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    groups:
      all:
        update-types: [minor, patch]
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    groups:
      all:
        update-types: [minor, patch]
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
