"""
实体类型映射 —— 单一数据源

统一维护中英文实体类型映射，消除 redactor / has_service / has_client / hybrid_vision_service 中的重复定义。
基于 GB/T 37964-2019《信息安全技术 个人信息去标识化指南》。
"""

# ──────────────────────────────────────────────
# 英文类型 ID → 中文标签（用于 smart 替换、提示等）
# ──────────────────────────────────────────────
TYPE_ID_TO_LABEL: dict[str, str] = {
    # 直接标识符
    "PERSON": "当事人",
    "ID_CARD": "证件号",
    "PASSPORT": "护照号",
    "PHONE": "电话",
    "EMAIL": "邮箱",
    "BANK_CARD": "账号",
    "BANK_ACCOUNT": "银行账号",
    "BANK_NAME": "开户行",
    "SOCIAL_SECURITY": "社保号",
    "WECHAT_ALIPAY": "支付账号",
    "IP_ADDRESS": "IP地址",
    "MAC_ADDRESS": "MAC地址",
    "DEVICE_ID": "设备号",
    "BIOMETRIC": "生物特征",
    "LEGAL_PARTY": "当事人",
    "LAWYER": "律师",
    "JUDGE": "法官",
    "WITNESS": "证人",
    # 准标识符
    "ORG": "公司",
    "COMPANY": "公司",
    "ADDRESS": "地址",
    "BIRTH_DATE": "出生日期",
    "DATE": "日期",
    "LICENSE_PLATE": "车牌",
    "CASE_NUMBER": "案号",
    "CONTRACT_NO": "编号",
    "COMPANY_CODE": "信用代码",
    "VIN": "车架号",
    # 敏感属性
    "AMOUNT": "金额",
    "HEALTH_INFO": "健康信息",
    "MEDICAL_RECORD": "病历号",
    "PROPERTY": "财产",
    "CRIMINAL_RECORD": "犯罪记录",
    # 通用
    "CUSTOM": "敏感信息",
}

# Backward-compatible aliases that must not be exposed or extracted as
# independent semantic types.
TYPE_ID_ALIASES: dict[str, str] = {
    "COMPANY": "ORG",
    "ORG_NAME": "ORG",
    "ORGANIZATION": "ORG",
    "ORGANIZATION_NAME": "ORG",
    "ORGANISATION": "ORG",
    "ORGANISATION_NAME": "ORG",
    "INSTITUTION": "ORG",
    "AGENCY": "ORG",
    "UNIT": "ORG",
    "EMPLOYER": "ORG",
    "WORKPLACE": "ORG",
    "TIME": "DATE",
    "DATETIME": "DATE",
    "DATE_TIME": "DATE",
    "DATE_AND_TIME": "DATE",
    "TIMESTAMP": "DATE",
    "TIME_STAMP": "DATE",
    "DATESTAMP": "DATE",
    "DATE_STAMP": "DATE",
    "MONEY": "AMOUNT",
}

# ──────────────────────────────────────────────
# 中文类型名 → 英文类型 ID（用于 HaS NER 结果转换）
# 支持多个中文别名映射到同一 ID
# ──────────────────────────────────────────────
TYPE_CN_TO_ID: dict[str, str] = {
    # 直接标识符
    "人名": "PERSON", "姓名": "PERSON", "名字": "PERSON",
    "账户名": "PERSON", "户名": "PERSON",
    "身份证号": "ID_CARD", "身份证": "ID_CARD", "身份证号码": "ID_CARD",
    "护照号": "PASSPORT", "护照": "PASSPORT", "护照号码": "PASSPORT",
    "电话号码": "PHONE", "电话": "PHONE", "手机号": "PHONE",
    "联系方式": "PHONE", "手机": "PHONE",
    "电子邮箱": "EMAIL", "邮箱": "EMAIL", "邮件": "EMAIL",
    "银行卡号": "BANK_CARD", "银行卡": "BANK_CARD", "卡号": "BANK_CARD",
    "银行账号": "BANK_ACCOUNT", "账号": "BANK_ACCOUNT",
    "账户号": "BANK_ACCOUNT", "账户号码": "BANK_ACCOUNT",
    "开户行": "BANK_NAME", "开户银行": "BANK_NAME",
    "银行名称": "BANK_NAME", "银行": "BANK_NAME",
    "社保号": "SOCIAL_SECURITY", "社保卡号": "SOCIAL_SECURITY",
    "医保号": "SOCIAL_SECURITY",
    # 准标识符
    "公司名称": "COMPANY", "公司": "COMPANY", "公司名": "COMPANY",
    "企业": "COMPANY", "企业名称": "COMPANY",
    "甲方": "COMPANY", "乙方": "COMPANY", "丙方": "COMPANY",
    "发包方": "COMPANY", "承包方": "COMPANY",
    "出借人": "COMPANY", "借款人": "COMPANY",
    "出卖人": "COMPANY", "买受人": "COMPANY",
    "委托方": "COMPANY", "受托方": "COMPANY",
    "供应商": "COMPANY", "承揽方": "COMPANY",
    "转让方": "COMPANY", "受让方": "COMPANY",
    "组织": "ORG", "机构名称": "ORG", "组织机构": "ORG",
    "机构": "ORG", "单位": "ORG",
    "工作单位": "WORK_UNIT", "所在单位": "WORK_UNIT", "任职单位": "WORK_UNIT",
    "地址": "ADDRESS", "详细地址": "ADDRESS",
    "住址": "ADDRESS", "居住地": "ADDRESS",
    "出生日期": "BIRTH_DATE", "生日": "BIRTH_DATE",
    "日期": "DATE", "日期时间": "DATE",
    "时间": "DATE", "时刻": "DATE", "时间点": "DATE",
    "车牌号": "LICENSE_PLATE", "车牌": "LICENSE_PLATE",
    "案件编号": "CASE_NUMBER", "案号": "CASE_NUMBER",
    "合同编号": "CASE_NUMBER", "合同号": "CASE_NUMBER",
    "统一社会信用代码": "COMPANY_CODE", "信用代码": "COMPANY_CODE",
    # 敏感属性
    "金额": "AMOUNT", "数额": "AMOUNT", "款项": "AMOUNT",
    # 法律文书
    "当事人": "LEGAL_PARTY", "原告": "LEGAL_PARTY", "被告": "LEGAL_PARTY",
    "律师": "LAWYER", "代理人": "LAWYER",
    "法官": "JUDGE", "审判长": "JUDGE", "书记员": "JUDGE",
    "证人": "WITNESS",
    # 文件/杂项
    "文件": "DOCUMENT",
    "密码": "PASSWORD",
}

# 反向映射：英文 ID → 首选中文名（取第一个匹配）
TYPE_ID_TO_LABEL.update({
    "USERNAME_PASSWORD": "登录账号",
    "URL_WEBSITE": "网址链接",
})

TYPE_ID_ALIASES.update({
    "PASSWORD": "USERNAME_PASSWORD",
    "ACCOUNT_PASSWORD": "USERNAME_PASSWORD",
    "USERNAME": "USERNAME_PASSWORD",
    "USER_NAME": "USERNAME_PASSWORD",
    "LOGIN_PASSWORD": "USERNAME_PASSWORD",
    "WEBSITE": "URL_WEBSITE",
    "URL": "URL_WEBSITE",
    "LINK": "URL_WEBSITE",
    "VIN_NUMBER": "VIN",
    "VEHICLE_VIN": "VIN",
    "VEHICLE_IDENTIFICATION_NUMBER": "VIN",
    "FRAME_NUMBER": "VIN",
    "CHASSIS_NUMBER": "VIN",
})

TYPE_CN_TO_ID.update({
    "密码": "USERNAME_PASSWORD",
    "登录账号": "USERNAME_PASSWORD",
    "账号密码": "USERNAME_PASSWORD",
    "账户密码": "USERNAME_PASSWORD",
    "用户名密码": "USERNAME_PASSWORD",
    "用户名_密码": "USERNAME_PASSWORD",
    "用户名/密码": "USERNAME_PASSWORD",
    "登录密码": "USERNAME_PASSWORD",
    "网址": "URL_WEBSITE",
    "链接": "URL_WEBSITE",
    "网址链接": "URL_WEBSITE",
    "网址_链接": "URL_WEBSITE",
    "网址/链接": "URL_WEBSITE",
})

TYPE_CN_TO_ID.update({
    "\u8f66\u67b6\u53f7": "VIN",
    "\u8f66\u67b6\u53f7_VIN": "VIN",
    "\u8f66\u67b6\u53f7/VIN": "VIN",
    "\u8f66\u8f86\u8bc6\u522b\u4ee3\u53f7": "VIN",
    "\u8f66\u8f86\u8bc6\u522b\u7801": "VIN",
})

TYPE_ID_TO_LABEL.update({
    "PERSON": "姓名",
    "ID_CARD": "身份证号",
    "PASSPORT": "护照号",
    "SOCIAL_SECURITY": "社保号",
    "BIOMETRIC": "生物特征",
    "PHONE": "电话",
    "EMAIL": "邮箱",
    "ADDRESS": "地址",
    "GPS_LOCATION": "定位位置",
    "USERNAME_PASSWORD": "登录账号",
    "AUTH_SECRET": "密码",
    "BANK_CARD": "银行卡号",
    "BANK_ACCOUNT": "银行账号",
    "BANK_NAME": "开户行",
    "AMOUNT": "金额",
    "DEVICE_ID": "设备号",
    "IP_ADDRESS": "IP地址",
    "URL_WEBSITE": "网址",
    "ORG": "组织机构",
    "DATE": "日期",
    "TIME": "时间",
    "AGE": "年龄",
    "GENDER": "性别",
    "NATIONALITY": "国籍",
    "ETHNICITY": "民族",
    "MARITAL_STATUS": "婚姻状态",
    "HEALTH_INFO": "健康信息",
    "RELIGION": "宗教信仰",
    "POLITICAL": "政治面貌",
    "SEXUAL_ORIENTATION": "性取向",
    "CASE_NUMBER": "编号",
    "CONTRACT_ID": "编号",
    "LICENSE_PLATE": "车牌号",
    "VIN": "车架号",
    "CRIMINAL_RECORD": "法律记录",
    "LEGAL_PLAINTIFF": "原告",
    "LEGAL_DEFENDANT": "被告",
    "LEGAL_THIRD_PARTY": "第三人",
    "LEGAL_COURT": "法院",
    "LEGAL_CASE_ID": "案号",
    "LEGAL_ATTORNEY": "代理律师",
    "LEGAL_LAW_FIRM": "律所",
    "LEGAL_CLAIM": "诉讼请求",
    "FIN_CUSTOMER_ID": "客户号",
    "FIN_ACCOUNT_NAME": "账户户名",
    "FIN_INSTITUTION": "金融机构",
    "FIN_TRANSACTION_ID": "交易流水号",
    "FIN_MERCHANT_ID": "商户号",
    "FIN_RISK_RATING": "风险评级",
    "MED_PATIENT": "患者",
    "MED_CLINICIAN": "医务人员",
    "MED_INSTITUTION": "医疗机构",
    "MED_DEPARTMENT": "科室",
    "MED_RECORD_ID": "病历号",
    "MED_DIAGNOSIS": "诊断",
    "MED_MEDICATION": "用药",
    "MED_EXAM_RESULT": "检查结果",
    "MED_CHIEF_COMPLAINT": "主诉",
    "MED_PRESENT_ILLNESS": "现病史",
    "MED_PAST_HISTORY": "既往史",
    "MED_ALLERGY_HISTORY": "过敏史",
    "MED_PROCEDURE": "医疗操作",
    "MED_ORDER": "医嘱",
    "MED_VITAL_SIGN": "生命体征",
})

for _type_id in (
    "PASSPORT", "SOCIAL_SECURITY", "BANK_ACCOUNT", "IP_ADDRESS", "URL_WEBSITE",
    "LICENSE_PLATE", "VIN", "TIME", "POLITICAL",
):
    TYPE_ID_ALIASES.pop(_type_id, None)

TYPE_ID_ALIASES.update({
    "DRIVER_LICENSE": "ID_CARD",
    "MILITARY_ID": "ID_CARD",
    "EMPLOYEE_ID": "ID_CARD",
    "QQ_WECHAT_ID": "USERNAME_PASSWORD",
    "ACCOUNT_NAME": "USERNAME_PASSWORD",
    "ACCOUNT_NUMBER": "USERNAME_PASSWORD",
    "CUSTOMER_ID": "USERNAME_PASSWORD",
    "MEMBER_ID": "USERNAME_PASSWORD",
    "PASSWORD": "AUTH_SECRET",
    "ACCOUNT_PASSWORD": "AUTH_SECRET",
    "LOGIN_PASSWORD": "AUTH_SECRET",
    "OTP": "AUTH_SECRET",
    "TOKEN": "AUTH_SECRET",
    "API_KEY": "AUTH_SECRET",
    "SECRET_KEY": "AUTH_SECRET",
    "PAYMENT_ACCOUNT": "BANK_ACCOUNT",
    "PAYMENT_ID": "BANK_ACCOUNT",
    "WALLET_ADDRESS": "BANK_ACCOUNT",
    "MONEY": "AMOUNT",
    "COMPANY": "ORG",
    "ORG_NAME": "ORG",
    "ORGANIZATION": "ORG",
    "ORGANIZATION_NAME": "ORG",
    "INSTITUTION": "ORG",
    "AGENCY": "ORG",
    "UNIT": "ORG",
    "EMPLOYER": "ORG",
    "BIRTH_DATE": "PERSONAL_ATTRIBUTE",
    "AGE": "PERSONAL_ATTRIBUTE",
    "GENDER": "PERSONAL_ATTRIBUTE",
    "NATIONALITY": "PERSONAL_ATTRIBUTE",
    "MARITAL_STATUS": "PERSONAL_ATTRIBUTE",
    "POSTAL_CODE": "ADDRESS",
    "LOCATION": "GPS_LOCATION",
    "GEO_LOCATION": "GPS_LOCATION",
    "MAC_ADDRESS": "DEVICE_ID",
    "URL": "URL_WEBSITE",
    "WEBSITE": "URL_WEBSITE",
    "LINK": "URL_WEBSITE",
    "COOKIE": "URL_WEBSITE",
    "MEDICAL_RECORD": "HEALTH_INFO",
    "CONTRACT_ID": "CASE_NUMBER",
    "CONTRACT_NO": "CASE_NUMBER",
    "CONTRACT_NUMBER": "CASE_NUMBER",
    "LEGAL_DOC_NO": "CASE_NUMBER",
    "VIN_NUMBER": "VIN",
    "VEHICLE_VIN": "VIN",
    "VEHICLE_IDENTIFICATION_NUMBER": "VIN",
    "FRAME_NUMBER": "VIN",
    "CHASSIS_NUMBER": "VIN",
    "LEGAL_PARTY": "PERSON",
    "LAWYER": "PERSON",
    "JUDGE": "PERSON",
    "WITNESS": "PERSON",
    "RELIGION": "POLITICAL",
    "SEXUAL_ORIENTATION": "POLITICAL",
    "GENETIC": "BIOMETRIC",
    "RACE_ETHNICITY": "PERSONAL_ATTRIBUTE",
    "UNION_MEMBERSHIP": "POLITICAL",
})

for _type_id in (
    "BIOMETRIC",
    "AGE",
    "GENDER",
    "NATIONALITY",
    "ETHNICITY",
    "MARITAL_STATUS",
    "RELIGION",
    "SEXUAL_ORIENTATION",
):
    TYPE_ID_ALIASES.pop(_type_id, None)

TYPE_ID_ALIASES.update({
    "RACE_ETHNICITY": "ETHNICITY",
    "GENETIC": "BIOMETRIC",
})

TYPE_CN_TO_ID.update({
    "姓名": "PERSON",
    "人名": "PERSON",
    "人员姓名": "PERSON",
    "身份证号": "ID_CARD",
    "身份证": "ID_CARD",
    "身份证号码": "ID_CARD",
    "护照号": "PASSPORT",
    "护照": "PASSPORT",
    "护照号码": "PASSPORT",
    "社保号": "SOCIAL_SECURITY",
    "社保卡号": "SOCIAL_SECURITY",
    "医保号": "SOCIAL_SECURITY",
    "电话": "PHONE",
    "电话号码": "PHONE",
    "手机号": "PHONE",
    "邮箱": "EMAIL",
    "电子邮箱": "EMAIL",
    "邮箱地址": "EMAIL",
    "地址": "ADDRESS",
    "住址": "ADDRESS",
    "收货地址": "ADDRESS",
    "通信地址": "ADDRESS",
    "定位位置": "GPS_LOCATION",
    "定位": "GPS_LOCATION",
    "经纬度": "GPS_LOCATION",
    "GPS坐标": "GPS_LOCATION",
    "账号": "USERNAME_PASSWORD",
    "账户": "USERNAME_PASSWORD",
    "用户名": "USERNAME_PASSWORD",
    "用户ID": "USERNAME_PASSWORD",
    "客户号": "USERNAME_PASSWORD",
    "会员号": "USERNAME_PASSWORD",
    "密码": "AUTH_SECRET",
    "验证码": "AUTH_SECRET",
    "密钥": "AUTH_SECRET",
    "令牌": "AUTH_SECRET",
    "Token": "AUTH_SECRET",
    "API Key": "AUTH_SECRET",
    "卡号": "BANK_CARD",
    "银行卡号": "BANK_CARD",
    "信用卡号": "BANK_CARD",
    "银行账号": "BANK_ACCOUNT",
    "对公账号": "BANK_ACCOUNT",
    "收款账号": "BANK_ACCOUNT",
    "支付账号": "BANK_ACCOUNT",
    "金额": "AMOUNT",
    "设备号": "DEVICE_ID",
    "设备标识": "DEVICE_ID",
    "终端号": "DEVICE_ID",
    "IP地址": "IP_ADDRESS",
    "网址": "URL_WEBSITE",
    "链接": "URL_WEBSITE",
    "域名": "URL_WEBSITE",
    "组织机构": "ORG",
    "机构名称": "ORG",
    "单位": "ORG",
    "单位名称": "ORG",
    "机构": "ORG",
    "组织": "ORG",
    "公司": "ORG",
    "公司名": "ORG",
    "公司名称": "ORG",
    "企业": "ORG",
    "企业名": "ORG",
    "企业名称": "ORG",
    "客户单位": "ORG",
    "供应商": "ORG",
    "甲方": "ORG",
    "乙方": "ORG",
    "丙方": "ORG",
    "开户行": "ORG",
    "开户银行": "ORG",
    "工作单位": "ORG",
    "所在单位": "ORG",
    "任职单位": "ORG",
    "日期": "DATE",
    "出生日期": "BIRTH_DATE",
    "生日": "BIRTH_DATE",
    "时间": "TIME",
    "时刻": "TIME",
    "年龄": "AGE",
    "年龄段": "AGE",
    "性别": "GENDER",
    "国籍": "NATIONALITY",
    "民族": "ETHNICITY",
    "族裔": "ETHNICITY",
    "种族": "ETHNICITY",
    "婚姻状态": "MARITAL_STATUS",
    "婚姻状况": "MARITAL_STATUS",
    "健康信息": "HEALTH_INFO",
    "医疗信息": "HEALTH_INFO",
    "病历号": "HEALTH_INFO",
    "业务编号": "CASE_NUMBER",
    "案件编号": "CASE_NUMBER",
    "合同编号": "CASE_NUMBER",
    "合同号": "CASE_NUMBER",
    "协议编号": "CASE_NUMBER",
    "协议号": "CASE_NUMBER",
    "保单号": "CASE_NUMBER",
    "订单号": "CASE_NUMBER",
    "工单号": "CASE_NUMBER",
    "车牌号": "LICENSE_PLATE",
    "车牌": "LICENSE_PLATE",
    "车架号": "VIN",
    "VIN": "VIN",
    "法律记录": "CRIMINAL_RECORD",
    "违法记录": "CRIMINAL_RECORD",
    "犯罪记录": "CRIMINAL_RECORD",
    "处罚记录": "CRIMINAL_RECORD",
    "原告": "LEGAL_PLAINTIFF",
    "申请人": "LEGAL_PLAINTIFF",
    "上诉人": "LEGAL_PLAINTIFF",
    "被告": "LEGAL_DEFENDANT",
    "被申请人": "LEGAL_DEFENDANT",
    "被上诉人": "LEGAL_DEFENDANT",
    "被执行人": "LEGAL_DEFENDANT",
    "第三人": "LEGAL_THIRD_PARTY",
    "案外人": "LEGAL_THIRD_PARTY",
    "利害关系人": "LEGAL_THIRD_PARTY",
    "法院": "LEGAL_COURT",
    "人民法院": "LEGAL_COURT",
    "仲裁机构": "LEGAL_COURT",
    "案号": "LEGAL_CASE_ID",
    "案件号": "LEGAL_CASE_ID",
    "执行案号": "LEGAL_CASE_ID",
    "代理律师": "LEGAL_ATTORNEY",
    "律师": "LEGAL_ATTORNEY",
    "辩护人": "LEGAL_ATTORNEY",
    "诉讼代理人": "LEGAL_ATTORNEY",
    "律所": "LEGAL_LAW_FIRM",
    "律师事务所": "LEGAL_LAW_FIRM",
    "诉讼请求": "LEGAL_CLAIM",
    "仲裁请求": "LEGAL_CLAIM",
    "执行请求": "LEGAL_CLAIM",
    "金融客户号": "FIN_CUSTOMER_ID",
    "投资者编号": "FIN_CUSTOMER_ID",
    "账户户名": "FIN_ACCOUNT_NAME",
    "开户名称": "FIN_ACCOUNT_NAME",
    "账户名称": "FIN_ACCOUNT_NAME",
    "金融机构": "FIN_INSTITUTION",
    "证券公司": "FIN_INSTITUTION",
    "保险公司": "FIN_INSTITUTION",
    "交易流水号": "FIN_TRANSACTION_ID",
    "流水号": "FIN_TRANSACTION_ID",
    "支付单号": "FIN_TRANSACTION_ID",
    "商户号": "FIN_MERCHANT_ID",
    "门店号": "FIN_MERCHANT_ID",
    "风险评级": "FIN_RISK_RATING",
    "风险等级": "FIN_RISK_RATING",
    "信用评级": "FIN_RISK_RATING",
    "患者": "MED_PATIENT",
    "受检者": "MED_PATIENT",
    "就诊人": "MED_PATIENT",
    "医务人员": "MED_CLINICIAN",
    "医生": "MED_CLINICIAN",
    "护士": "MED_CLINICIAN",
    "医疗机构": "MED_INSTITUTION",
    "医院": "MED_INSTITUTION",
    "诊所": "MED_INSTITUTION",
    "科室": "MED_DEPARTMENT",
    "病区": "MED_DEPARTMENT",
    "门诊号": "MED_RECORD_ID",
    "住院号": "MED_RECORD_ID",
    "诊断": "MED_DIAGNOSIS",
    "疾病": "MED_DIAGNOSIS",
    "用药": "MED_MEDICATION",
    "药品": "MED_MEDICATION",
    "检查结果": "MED_EXAM_RESULT",
    "检验结果": "MED_EXAM_RESULT",
    "主诉": "MED_CHIEF_COMPLAINT",
    "现病史": "MED_PRESENT_ILLNESS",
    "既往史": "MED_PAST_HISTORY",
    "过敏史": "MED_ALLERGY_HISTORY",
    "医疗操作": "MED_PROCEDURE",
    "手术": "MED_PROCEDURE",
    "医嘱": "MED_ORDER",
    "生命体征": "MED_VITAL_SIGN",
    "血压": "MED_VITAL_SIGN",
    "体温": "MED_VITAL_SIGN",
    "政治面貌": "POLITICAL",
    "政治观点": "POLITICAL",
    "宗教信仰": "RELIGION",
    "宗教": "RELIGION",
    "信仰": "RELIGION",
    "性取向": "SEXUAL_ORIENTATION",
    "性生活": "SEXUAL_ORIENTATION",
    "生物特征": "BIOMETRIC",
    "指纹": "BIOMETRIC",
    "声纹": "BIOMETRIC",
    "虹膜": "BIOMETRIC",
    "基因信息": "BIOMETRIC",
})

TYPE_ID_TO_CN: dict[str, str] = {}
for _cn, _id in TYPE_CN_TO_ID.items():
    _normalized_id = str(_id or "").strip().upper().replace("-", "_").replace(" ", "_").replace("/", "_")
    _canonical_id = TYPE_ID_ALIASES.get(_normalized_id, _normalized_id)
    if _normalized_id == _canonical_id and _canonical_id not in TYPE_ID_TO_CN:
        TYPE_ID_TO_CN[_canonical_id] = _cn
for _cn, _id in TYPE_CN_TO_ID.items():
    _normalized_id = str(_id or "").strip().upper().replace("-", "_").replace(" ", "_").replace("/", "_")
    _canonical_id = TYPE_ID_ALIASES.get(_normalized_id, _normalized_id)
    if _canonical_id not in TYPE_ID_TO_CN:
        TYPE_ID_TO_CN[_canonical_id] = _cn

TYPE_ID_TO_CN.update({
    "PERSON": "姓名",
    "ID_CARD": "身份证号",
    "PASSPORT": "护照号",
    "SOCIAL_SECURITY": "社保号",
    "BIOMETRIC": "生物特征",
    "PHONE": "电话",
    "EMAIL": "邮箱",
    "ADDRESS": "地址",
    "GPS_LOCATION": "定位位置",
    "USERNAME_PASSWORD": "登录账号",
    "AUTH_SECRET": "密码",
    "BANK_CARD": "银行卡号",
    "BANK_ACCOUNT": "银行账号",
    "BANK_NAME": "开户行",
    "AMOUNT": "金额",
    "DEVICE_ID": "设备号",
    "IP_ADDRESS": "IP地址",
    "URL_WEBSITE": "网址",
    "ORG": "组织机构",
    "DATE": "日期",
    "TIME": "时间",
    "AGE": "年龄",
    "GENDER": "性别",
    "NATIONALITY": "国籍",
    "ETHNICITY": "民族",
    "MARITAL_STATUS": "婚姻状态",
    "HEALTH_INFO": "健康信息",
    "RELIGION": "宗教信仰",
    "POLITICAL": "政治面貌",
    "SEXUAL_ORIENTATION": "性取向",
    "CASE_NUMBER": "编号",
    "CONTRACT_ID": "编号",
    "LICENSE_PLATE": "车牌号",
    "VIN": "车架号",
    "CRIMINAL_RECORD": "法律记录",
    "LEGAL_PLAINTIFF": "原告",
    "LEGAL_DEFENDANT": "被告",
    "LEGAL_THIRD_PARTY": "第三人",
    "LEGAL_COURT": "法院",
    "LEGAL_CASE_ID": "案号",
    "LEGAL_ATTORNEY": "代理律师",
    "LEGAL_LAW_FIRM": "律所",
    "LEGAL_CLAIM": "诉讼请求",
    "FIN_CUSTOMER_ID": "客户号",
    "FIN_ACCOUNT_NAME": "账户户名",
    "FIN_INSTITUTION": "金融机构",
    "FIN_TRANSACTION_ID": "交易流水号",
    "FIN_MERCHANT_ID": "商户号",
    "FIN_RISK_RATING": "风险评级",
    "MED_PATIENT": "患者",
    "MED_CLINICIAN": "医务人员",
    "MED_INSTITUTION": "医疗机构",
    "MED_DEPARTMENT": "科室",
    "MED_RECORD_ID": "病历号",
    "MED_DIAGNOSIS": "诊断",
    "MED_MEDICATION": "用药",
    "MED_EXAM_RESULT": "检查结果",
    "MED_CHIEF_COMPLAINT": "主诉",
    "MED_PRESENT_ILLNESS": "现病史",
    "MED_PAST_HISTORY": "既往史",
    "MED_ALLERGY_HISTORY": "过敏史",
    "MED_PROCEDURE": "医疗操作",
    "MED_ORDER": "医嘱",
    "MED_VITAL_SIGN": "生命体征",
})

# Final public schema corrections.
# These are first-class generic entity types and must not collapse into ORG,
# broad organization or case-number buckets. HaS receives these Chinese labels directly.
for _type_id in (
    "COMPANY",
    "COMPANY_NAME",
    "ORG_NAME",
    "ORGANIZATION",
    "ORGANIZATION_NAME",
    "ORGANISATION",
    "ORGANISATION_NAME",
    "INSTITUTION",
    "INSTITUTION_NAME",
    "AGENCY",
    "UNIT",
    "EMPLOYER",
    "WORK_UNIT",
    "COMPANY_CODE",
    "TAX_ID",
    "CONTRACT_ID",
    "CONTRACT_NO",
    "CONTRACT_NUMBER",
):
    TYPE_ID_ALIASES.pop(_type_id, None)

TYPE_ID_ALIASES.update({
    "COMPANY": "COMPANY_NAME",
    "ORG_NAME": "ORG",
    "ORGANIZATION": "ORG",
    "ORGANIZATION_NAME": "ORG",
    "ORGANISATION": "ORG",
    "ORGANISATION_NAME": "ORG",
    "COMPANY_CODE": "CREDIT_CODE",
    "CONTRACT_ID": "CASE_NUMBER",
    "CONTRACT_NO": "CASE_NUMBER",
    "CONTRACT_NUMBER": "CASE_NUMBER",
})

TYPE_ID_TO_LABEL.update({
    "ORG": "组织机构",
    "COMPANY_NAME": "公司名称",
    "INSTITUTION_NAME": "机构名称",
    "GOVERNMENT_AGENCY": "机关单位",
    "WORK_UNIT": "工作单位",
    "DEPARTMENT_NAME": "部门名称",
    "PROJECT_NAME": "项目名称",
    "CREDIT_CODE": "统一社会信用代码",
    "TAX_ID": "税号",
    "CASE_NUMBER": "编号",
})

TYPE_CN_TO_ID.update({
    "组织机构": "ORG",
    "公司名称": "COMPANY_NAME",
    "公司名": "COMPANY_NAME",
    "公司": "COMPANY_NAME",
    "企业名称": "COMPANY_NAME",
    "企业名": "COMPANY_NAME",
    "企业": "COMPANY_NAME",
    "机构名称": "INSTITUTION_NAME",
    "机构": "INSTITUTION_NAME",
    "单位名称": "INSTITUTION_NAME",
    "机关单位": "GOVERNMENT_AGENCY",
    "政府机关": "GOVERNMENT_AGENCY",
    "监管部门": "GOVERNMENT_AGENCY",
    "行政机关": "GOVERNMENT_AGENCY",
    "工作单位": "WORK_UNIT",
    "所在单位": "WORK_UNIT",
    "任职单位": "WORK_UNIT",
    "就职单位": "WORK_UNIT",
    "部门名称": "DEPARTMENT_NAME",
    "部门": "DEPARTMENT_NAME",
    "科室": "DEPARTMENT_NAME",
    "处室": "DEPARTMENT_NAME",
    "项目组": "DEPARTMENT_NAME",
    "项目名称": "PROJECT_NAME",
    "项目": "PROJECT_NAME",
    "课题名称": "PROJECT_NAME",
    "统一社会信用代码": "CREDIT_CODE",
    "信用代码": "CREDIT_CODE",
    "税号": "TAX_ID",
    "纳税人识别号": "TAX_ID",
    "税务登记号": "TAX_ID",
    "编号": "CASE_NUMBER",
    "业务编号": "CASE_NUMBER",
    "案号": "CASE_NUMBER",
    "案件编号": "CASE_NUMBER",
    "案件号": "CASE_NUMBER",
    "执行案号": "CASE_NUMBER",
    "合同编号": "CASE_NUMBER",
    "合同号": "CASE_NUMBER",
    "协议编号": "CASE_NUMBER",
    "协议号": "CASE_NUMBER",
    "保单号": "CASE_NUMBER",
})

TYPE_ID_TO_CN.update({
    "ORG": "组织机构",
    "COMPANY_NAME": "公司名称",
    "INSTITUTION_NAME": "机构名称",
    "GOVERNMENT_AGENCY": "机关单位",
    "WORK_UNIT": "工作单位",
    "DEPARTMENT_NAME": "部门名称",
    "PROJECT_NAME": "项目名称",
    "CREDIT_CODE": "统一社会信用代码",
    "TAX_ID": "税号",
    "CASE_NUMBER": "编号",
})

# Maintained taxonomy corrections. Business labels must not collapse into broad
# buckets for linkage; linkage uses semantic groups below.
for _type_id in (
    "COMPANY",
    "INSTITUTION",
    "AGENCY",
    "UNIT",
    "EMPLOYER",
    "WORKPLACE",
    "BANK_NAME",
    "MEDICAL_RECORD",
    "LAWYER",
    "JUDGE",
    "WITNESS",
):
    TYPE_ID_ALIASES.pop(_type_id, None)

TYPE_ID_ALIASES.update({
    "HEALTH_INFO": "MED_DIAGNOSIS",
    "MEDICAL_INFO": "MED_DIAGNOSIS",
    "COMPANY": "COMPANY_NAME",
    "INSTITUTION": "INSTITUTION_NAME",
    "EMPLOYER": "WORK_UNIT",
    "WORKPLACE": "WORK_UNIT",
    "MEDICAL_RECORD": "MED_RECORD_ID",
    "LAWYER": "LEGAL_ATTORNEY",
})

TYPE_CN_TO_ID.update({
    "健康信息": "MED_DIAGNOSIS",
    "医疗信息": "MED_DIAGNOSIS",
    "病历号": "MED_RECORD_ID",
    "名称": "GEN_NAME",
    "通用名称": "GEN_NAME",
    "号码": "GEN_NUMBER_CODE",
    "编号": "GEN_NUMBER_CODE",
    "代码": "GEN_NUMBER_CODE",
    "号码/编号/代码": "GEN_NUMBER_CODE",
    "联系方式": "GEN_CONTACT",
    "地址位置": "GEN_ADDRESS_LOCATION",
    "日期时间": "GEN_DATE_TIME",
    "账户与交易": "GEN_ACCOUNT_TRANSACTION",
    "金额数值": "GEN_AMOUNT_VALUE",
    "凭证密钥与访问控制": "GEN_CREDENTIAL_ACCESS",
    "人员主体": "GEN_PERSON_SUBJECT",
    "组织主体": "GEN_ORGANIZATION_SUBJECT",
    "属性状态": "GEN_ATTRIBUTE_STATUS",
    "文档内容与业务记录": "GEN_DOCUMENT_RECORD",
    "资产资源与标的物": "GEN_ASSET_RESOURCE",
    "视觉语义补充": "GEN_VISUAL_SEMANTIC",
    "开户行": "BANK_NAME",
    "开户银行": "BANK_NAME",
    "收款银行": "BANK_NAME",
    "银行名称": "BANK_NAME",
    "公司": "COMPANY_NAME",
    "公司名": "COMPANY_NAME",
    "公司名称": "COMPANY_NAME",
    "企业": "COMPANY_NAME",
    "企业名": "COMPANY_NAME",
    "企业名称": "COMPANY_NAME",
    "甲方": "COMPANY_NAME",
    "乙方": "COMPANY_NAME",
    "丙方": "COMPANY_NAME",
    "供应商": "COMPANY_NAME",
    "客户单位": "COMPANY_NAME",
    "机构": "INSTITUTION_NAME",
    "机构名称": "INSTITUTION_NAME",
    "单位": "INSTITUTION_NAME",
    "单位名称": "INSTITUTION_NAME",
    "工作单位": "WORK_UNIT",
    "所在单位": "WORK_UNIT",
    "任职单位": "WORK_UNIT",
    "就职单位": "WORK_UNIT",
    "就诊号": "MED_RECORD_ID",
    "律师": "LEGAL_ATTORNEY",
    "代理律师": "LEGAL_ATTORNEY",
})

TYPE_ID_TO_LABEL.update({
    "GEN_NAME": "名称",
    "GEN_NUMBER_CODE": "号码/编号/代码",
    "GEN_CONTACT": "联系方式",
    "GEN_ADDRESS_LOCATION": "地址位置",
    "GEN_DATE_TIME": "日期时间",
    "GEN_ACCOUNT_TRANSACTION": "账户与交易",
    "GEN_AMOUNT_VALUE": "金额数值",
    "GEN_CREDENTIAL_ACCESS": "凭证密钥与访问控制",
    "GEN_PERSON_SUBJECT": "人员主体",
    "GEN_ORGANIZATION_SUBJECT": "组织主体",
    "GEN_ATTRIBUTE_STATUS": "属性状态",
    "GEN_DOCUMENT_RECORD": "文档内容与业务记录",
    "GEN_ASSET_RESOURCE": "资产资源与标的物",
    "GEN_VISUAL_SEMANTIC": "视觉语义补充",
})

TYPE_ID_TO_CN.update({
    "GEN_NAME": "名称",
    "GEN_NUMBER_CODE": "号码/编号/代码",
    "GEN_CONTACT": "联系方式",
    "GEN_ADDRESS_LOCATION": "地址位置",
    "GEN_DATE_TIME": "日期时间",
    "GEN_ACCOUNT_TRANSACTION": "账户与交易",
    "GEN_AMOUNT_VALUE": "金额数值",
    "GEN_CREDENTIAL_ACCESS": "凭证密钥与访问控制",
    "GEN_PERSON_SUBJECT": "人员主体",
    "GEN_ORGANIZATION_SUBJECT": "组织主体",
    "GEN_ATTRIBUTE_STATUS": "属性状态",
    "GEN_DOCUMENT_RECORD": "文档内容与业务记录",
    "GEN_ASSET_RESOURCE": "资产资源与标的物",
    "GEN_VISUAL_SEMANTIC": "视觉语义补充",
})

TYPE_ID_ALIASES.pop("BIRTH_DATE", None)
TYPE_ID_ALIASES.update({
    "LEGAL_CASE_ID": "DOCUMENT_NUMBER",
    "LEGAL_DOC_NO": "DOCUMENT_NUMBER",
})

TYPE_ID_TO_LABEL.update({
    "BIRTH_DATE": "出生日期",
    "DOCUMENT_NUMBER": "文书编号",
})

TYPE_ID_TO_CN.update({
    "BIRTH_DATE": "出生日期",
    "DOCUMENT_NUMBER": "文书编号",
})

TYPE_CN_TO_ID.update({
    "出生日期": "BIRTH_DATE",
    "生日": "BIRTH_DATE",
    "文书编号": "DOCUMENT_NUMBER",
    "文书号": "DOCUMENT_NUMBER",
    "法律文书号": "DOCUMENT_NUMBER",
    "裁判文书编号": "DOCUMENT_NUMBER",
    "案号": "DOCUMENT_NUMBER",
    "案件号": "DOCUMENT_NUMBER",
    "执行案号": "DOCUMENT_NUMBER",
})

LINKAGE_GROUP_BY_TYPE_ID: dict[str, set[str]] = {
    "GEN_ORGANIZATION_SUBJECT": {"organization_like"},
    "ORG": {"organization_like"},
    "COMPANY_NAME": {"organization_like"},
    "INSTITUTION_NAME": {"organization_like"},
    "GOVERNMENT_AGENCY": {"organization_like"},
    "WORK_UNIT": {"organization_like"},
    "DEPARTMENT_NAME": {"organization_like"},
    "PROJECT_NAME": {"organization_like"},
    "FIN_INSTITUTION": {"organization_like"},
    "BANK_NAME": {"organization_like", "account_like"},
    "MED_INSTITUTION": {"organization_like"},
    "MED_DEPARTMENT": {"organization_like"},
    "LEGAL_COURT": {"organization_like"},
    "LEGAL_LAW_FIRM": {"organization_like"},
    "GEN_PERSON_SUBJECT": {"person_like"},
    "PERSON": {"person_like"},
    "ID_CARD": {"identifier_like", "person_like"},
    "PASSPORT": {"identifier_like", "person_like"},
    "SOCIAL_SECURITY": {"identifier_like", "person_like"},
    "PHONE": {"person_like"},
    "EMAIL": {"person_like"},
    "AGE": {"person_like"},
    "GENDER": {"person_like"},
    "NATIONALITY": {"person_like"},
    "ETHNICITY": {"person_like"},
    "MARITAL_STATUS": {"person_like"},
    "RELIGION": {"person_like"},
    "POLITICAL": {"person_like"},
    "SEXUAL_ORIENTATION": {"person_like"},
    "CRIMINAL_RECORD": {"person_like"},
    "LEGAL_PLAINTIFF": {"person_like", "organization_like"},
    "LEGAL_DEFENDANT": {"person_like", "organization_like"},
    "LEGAL_THIRD_PARTY": {"person_like", "organization_like"},
    "LEGAL_ATTORNEY": {"person_like"},
    "MED_PATIENT": {"person_like"},
    "MED_CLINICIAN": {"person_like"},
    "GEN_ACCOUNT_TRANSACTION": {"account_like"},
    "GEN_AMOUNT_VALUE": {"account_like"},
    "BANK_CARD": {"account_like"},
    "BANK_ACCOUNT": {"account_like"},
    "FIN_ACCOUNT_NAME": {"account_like"},
    "FIN_CUSTOMER_ID": {"account_like"},
    "FIN_TRANSACTION_ID": {"account_like"},
    "FIN_MERCHANT_ID": {"account_like"},
    "AMOUNT": {"account_like"},
    "GEN_NUMBER_CODE": {"identifier_like"},
    "CASE_NUMBER": {"identifier_like"},
    "DOCUMENT_NUMBER": {"identifier_like"},
    "MED_RECORD_ID": {"identifier_like"},
    "CREDIT_CODE": {"identifier_like", "organization_like"},
    "TAX_ID": {"identifier_like", "organization_like"},
    "LICENSE_PLATE": {"identifier_like"},
    "VIN": {"identifier_like"},
    "GEN_ADDRESS_LOCATION": {"address_like"},
    "ADDRESS": {"address_like"},
    "GPS_LOCATION": {"address_like"},
    "GEN_DATE_TIME": {"date_like"},
    "BIRTH_DATE": {"date_like", "person_like"},
    "DATE": {"date_like"},
    "TIME": {"date_like"},
    "GEN_CREDENTIAL_ACCESS": {"credential_like"},
    "USERNAME_PASSWORD": {"credential_like"},
    "AUTH_SECRET": {"credential_like"},
    "DEVICE_ID": {"credential_like", "identifier_like"},
    "IP_ADDRESS": {"credential_like", "identifier_like"},
    "URL_WEBSITE": {"credential_like", "identifier_like"},
}


def linkage_groups_for_type(type_id: str) -> set[str]:
    """Return internal linkage groups without changing the public type id."""
    canonical = canonical_type_id(type_id)
    return set(LINKAGE_GROUP_BY_TYPE_ID.get(canonical, set()))


def linkage_group_for_type(type_id: str) -> str:
    """Return a stable primary linkage group for legacy single-group callers."""
    groups = linkage_groups_for_type(type_id)
    return sorted(groups)[0] if groups else ""


def cn_to_id(chinese_type: str) -> str:
    """中文类型名转英文 ID，未知类型返回大写原文。"""
    return canonical_type_id(TYPE_CN_TO_ID.get(chinese_type, chinese_type.upper()))


def id_to_label(type_id: str, default: str = "敏感信息") -> str:
    """英文类型 ID 转中文标签，用于 smart 替换。"""
    return TYPE_ID_TO_LABEL.get(canonical_type_id(type_id), default)


def id_to_cn(type_id: str) -> str:
    """英文类型 ID 转中文类型名（用于 HaS prompt）。"""
    canonical = canonical_type_id(type_id)
    return TYPE_ID_TO_CN.get(canonical, canonical)


def canonical_type_id(type_id: str) -> str:
    """Return the canonical public type ID for deprecated aliases."""
    normalized = str(type_id or "").strip().upper().replace("-", "_").replace(" ", "_").replace("/", "_")
    return TYPE_ID_ALIASES.get(normalized, normalized)


def canonical_type_ids(type_ids: list[str | None] | tuple[str | None, ...]) -> list[str]:
    """Return stable de-duplicated canonical type IDs."""
    canonical_ids: list[str] = []
    seen: set[str] = set()
    for type_id in type_ids:
        canonical = canonical_type_id(type_id or "")
        if canonical and canonical not in seen:
            seen.add(canonical)
            canonical_ids.append(canonical)
    return canonical_ids
